# Required metadata
sonar.projectKey=docker-security-lab
sonar.organization=gurumech07
sonar.host.url=https://sonarcloud.io
sonar.verbose=true

# Path to source directory
sonar.sources=.

# Exclusions
sonar.exclusions=**/tests/**, **/Dockerfile.std

# Language-specific
sonar.python.version=3.11

# Encoding
sonar.sourceEncoding=UTF-8
