# Required metadata
sonar.projectKey=gurumech07_docker-security-lab
sonar.organization=gurumech07

# Path to source directory
sonar.sources=.

# Exclusions
sonar.exclusions=**/tests/**, **/Dockerfile.std

# Language-specific
sonar.python.version=3.11
sonar.python.bandit.reportPaths=bandit-report.json

# Encoding
sonar.sourceEncoding=UTF-8
