name: Security Analysis & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=gurumech07_docker-security-lab
            -Dsonar.organization=gurumech07
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security-and-publish:
    name: Security Scan, Compare & Publish
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Images
        run: |
          docker build -t security-lab:std -f Dockerfile.std .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/security-lab:hardened -f Dockerfile .

      - name: Docker Scout Comparison
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ secrets.DOCKERHUB_USERNAME }}/security-lab:hardened
          to: security-lab:std
          ignore-unchanged: false
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_HUB_PAT: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Hardened Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/security-lab:hardened
